### ISSUE TITLE
$digest already in progress

### ISSUE THREAD

**Issue by savicprvoslav** [lght/angular-scroll-pane#1]
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.2.26/$rootScope/inprog?p0=%24digest
    at angular.js:78
    at beginPhase (angular.js:13010)
    at Scope.$apply (angular.js:12799)
    at angular-jscrollpane.min.js:2
    at Scope.$broadcast (angular.js:12981)
    at main.js:402
    at wrappedCallback (angular.js:11573)
    at wrappedCallback (angular.js:11573)
    at angular.js:11659
    at Scope.$eval (angular.js:12702)

$scope.$broadcast('reinit-pane',"id of the scroll pane");

**Comment by geoffreybauduin** [comment]
Can you provide the context where you call `$scope.broadcast` ?

**Comment by savicprvoslav** [comment]
Logic would be something like this:

$resource.get(function(data){
$scope.data=data...

   -> here i make broadcast after data is set.
})

**Comment by pencilcheck** [comment]
I used $timeout with 0 and the digest error disappears
