### ISSUE TITLE
using directive in ng-repeat

### ISSUE THREAD

**Issue by rgi2000** [lght/angular-scroll-pane#2]
I'm having problem using this directive within ng-repeat.  It only works the first time in ng-repeat?  Probably it has something to do with the fact that is is not unique to all elements.  I've tried to create unique ID as id="Div1_{{$index}}" but this doesn't work.  Any suggestions how to make it work within ng-repeat?
![capture](https://cloud.githubusercontent.com/assets/5229030/8747033/25392ffc-2c5d-11e5-87b5-05ba4ffa3278.PNG)

![capture1](https://cloud.githubusercontent.com/assets/5229030/8747092/abea67a0-2c5d-11e5-8e41-37cf7a8b889f.PNG)

**Comment by geoffreybauduin** [comment]
Can you provide a code snippet on some website like Plunkr?

**Comment by rgi2000** [comment]
Here is a link to Plunkr.

http://plnkr.co/edit/RdMZZJFBfE82wXhtOFXM

The question is how do I "beautify" vertical scroll bar for second and third item in ng-repeat?

Thanks.

**Comment by geoffreybauduin** [comment]
I just fixed the problem. You can add a `scroll-name` parameter, for example `scroll-name="scrollPane{{$index}}"`
