### ISSUE TITLE
bower.json dependency for angular change

### ISSUE THREAD

**Issue by pencilcheck** [lght/angular-scroll-pane#5]
This technically is a bug belongs to bower but I would like to ask the Arthur to change the dependency for angular from "angularjs" to "angular", otherwise bower will download and load two identical angular js library (they just named differently) into the bower_components and since I use gulp to automate adding the library into index.html angular are being loaded twice.

**Comment by geoffreybauduin** [comment]
I will give it a look later in the day, thanks for your feedback!

**Comment by Baloobear** [comment]
+1 for the change of the angularjs dependency, plz

**Comment by geoffreybauduin** [comment]
Sorry for the delay guys, I just bumped the library version
